apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  labels:
    app: auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels: 
      component: auth
  template:
    metadata:
      labels:
        component: auth        
    spec:
      containers:
      - name: auth-service
        image: shakka/auth-user-service
        # uncomment this line to reference local build of image
        # image: auth-user-service
        imagePullPolicy: IfNotPresent
        env:
          - name: PORT
            value: '3000'
          - name: DB_URL
            valueFrom:
              secretKeyRef:
                name: db-secrets
                key: db-url
          - name: PRIVATE_KEY
            valueFrom:
              secretKeyRef:
                name: key-secrets
                key: private
        # Override start command for enabling of debugging
        command: ['node']
        args: ['--inspect', 'server.js']
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
          limits:
            memory: "300Mi"
            cpu: "300m"
        ports:
          - name: auth-port 
            containerPort: 3000

 
