apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-deployment
  labels:
    app: post-deployment
spec:
  replicas: 1
  selector:
    matchLabels: 
      component: post
  template:
    metadata:
      labels:
        component: post
    spec:
      containers:
      - name: post-service
        # image: shakka/post-service
        # uncomment this line to reference local build of image
        image: post-service
        imagePullPolicy: IfNotPresent
        env:
          - name: PORT
            value: '3000'
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: db-secrets
                key: database_url
        # Override start command for enabling of debugging
        command: ['node']
        args: ['--inspect', 'server.js']
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
          limits:
            memory: "300Mi"
            cpu: "300m"
        ports:
          - name: post-port 
            containerPort: 3000

 
