apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-deployment
  labels:
    app: post-deployment
    serviceRoute: post
    serviceName: post-service
spec:
  replicas: 1
  selector:
    matchLabels: 
      component: post
  template:
    metadata:
      labels:
        component: post
        serviceRoute: post
        serviceName: post-service
    spec:
      containers:
      - name: post-service
        image: shakka/post-service
        env:
          - name: PORT
            value: '3001'
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: db-secrets
                key: database_url
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
          limits:
            memory: "300Mi"
            cpu: "300m"
        ports:
          - name: post-port 
            containerPort: 3001

 
