apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: postgres-db
  name: postgres
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  selector:
    matchLabels:
    
      component: postgres
  serviceName: postgres
  template:
    metadata:
      labels:
        app: postgres-db
        component: postgres
    spec:
      volumes:
        - name: db-storage
          persistentVolumeClaim:
            claimName: db-pvc
        - name: config-db-volume
          configMap:
            name: db-config
            items:
            - key: post_service.sql
              path: post_service.sql
            - key: user_service.sql
              path: user_service.sql
      containers:
      - name: postgres
        image: postgres
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"
          requests:
            memory: "128Mi"
            cpu: "100m"
        ports:
          - name: db-port
            containerPort: 5432
        volumeMounts:
          - name: db-storage
            mountPath: /var/lib/postgresql/data
            subPath: postgres
          - name: config-db-volume
            mountPath: /docker-entrypoint-initdb.d/
      
