apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: helloworld-rules
spec:
  rules:
    - http:
        paths:
        - path: /
          backend:
            serviceName: gateway-service
            servicePort: 3001