apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-datadir
spec: 
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage:
        1Gi