apiVersion: v1
kind: Service
metadata:
  name: auth-service
  labels:
    serviceRoute: auth
    serviceName: auth-service
spec:
  selector:
    component: auth
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
