apiVersion: v1
kind: Service
metadata:
  name: post-service
  labels: 
    serviceRoute: post
    serviceName: post-service
spec:
  selector:
    component: post
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
