apiVersion: v1
kind: Service
metadata:
  name: upload-service
  labels:
    serviceRoute: upload
    serviceName: upload-service
spec:
  selector:
    component: upload
  ports:
  - port: 3000
    targetPort: upload-port
    protocol: TCP
