apiVersion: v1
kind: Pod
metadata:
  name: gateway-pod
  labels:
    app: gateway
spec:
  containers:
  - name: api-gateway
    image: shakka/api-gateway
    env:
      - name: PORT
        value: '3001'
      - name: PUBLIC_KEY
        valueFrom:
          secretKeyRef:
            name: key-secrets
            key: public
    
    resources:
      limits:
        memory: "128Mi"
        cpu: "200m"
      requests:
        memory: "128Mi"
        cpu: "100m"
    ports:
      - name: gateway-port 
        containerPort: 3001
    volumeMounts:
      - mountPath: /var/run/docker.sock
        name: docker-sock-volume
  volumes:
  - name: docker-sock-volume
    hostPath:
      path: /var/run/docker.sock
      type: File