apiVersion: v1
kind: Pod
metadata:
  name: auth-pod
  labels:
    app: auth
    serviceRoute: auth
    serviceName: auth-service
spec:
  containers:
  - name: auth-service
    image: shakka/auth-user-service
    env:
      - name: PORT
        value: '3001'
    resources:
      requests:
        memory: "100Mi"
        cpu: "100m"
      limits:
        memory: "300Mi"
        cpu: "300m"
    ports:
      - name: auth-port 
        containerPort: 3001

 
