apiVersion: v1
kind: Pod
metadata:
  name: reverse-proxy-pod
  labels:
    app: nginx
spec:
  containers:
  - name: reverse-proxy
    image: nginx:alpine
    resources:
      limits:
        memory: "128Mi"
        cpu: "200m"
      requests:
        memory: "128Mi"
        cpu: "100m"
    ports:
      - name: proxy-port
        containerPort: 80
    volumeMounts:
      - name: reverse-proxy-config-volume
        mountPath: /etc/nginx/conf.d/
  volumes:
    - name: reverse-proxy-config-volume
      configMap:
        name: reverse-proxy-config
        items:
        - key: default.conf
          path: default.conf
